### PR TITLE
Move package under @lingui namespace

### PR DESCRIPTION
**Pull request by tricoder42**
Hey @semoal, could I move the package under `@lingui` namespace in npmjs? I would add your as a team member so you could publish new versions on your will.

I've updated `package.json` and `README.md` with the new package name.

### CODE REVIEW

**Comment by semoal** [comment]
Yes, absolutly i did like that on a first instance if you were too busy to give some time to setup the publish action, but the best way is like that :)

**Comment by tricoder42** [comment]
I've never did that before. I publish all `@lingui/*` packages manually because I use 2FA, but for this repo it should be fine. Let me check how to do that

**Comment by semoal** [comment]
You can publish it manually to let the users use it, and in parallel i'll setup all the things to enable automatic versionaing, generating changelog etc...

I'm my packages I got this setup and is amazing :)

**Comment by tricoder42** [comment]
Alright, let's do this. I'm gonna publish it as it is now. Thanks a lot!

I've dived into `semantic-release` few years back but never actually made it work for my usecase... Keep to learn something new :)

**Comment by tricoder42** [comment]
Package was just published: https://www.npmjs.com/package/@lingui/codemods/v/latest

Not sure if you'll need to setup 2FA for publishing. Please let me know, otherwise I'm gonna disable it for the whole org.

**Pull request merged**
